[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
annotate-snippets = "0.11.5"
clap = { version = "4.5.39", features = ["derive"] }
flate2 = { version = "1.1.1", features = ["zlib-rs"], default-features = false }
winnow = "0.7.10"
